import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fontsource/inter";
import "@fontsource/poppins";
import TopNavigation from "@/components/TopNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-pink-50 font-sans antialiased text-neutral-900">
        <TopNavigation />
        <div className="max-w-5xl mx-auto w-full px-4 pt-8">
          {children}
        </div>
      </body>
    </html>
  );
}
